### ISSUE TITLE
Question about Figure 1, 3 on the LPKT paper

### ISSUE THREAD

**Issue by kwonmha** [bigdata-ustc/EduKTM#29]
Hello, Thanks for opening codes for this project.
I want to check the proficiency change of every knowledge during learning process as in the figure 1, 3. of your LPKT paper.
How did you get the proficiency level from 0.0 to 1.0?

**Comment by shshen-closer** [comment]
Thanks for your attention. In LPKT (figure 3), for a specific KC, we have its proficiency  vector in the knowledge matrix, just sum the proficiency  vector and output a proficiency  value, then use a logistic function to project it from 0.0 to 1.0. Here you need to try a proper logistic function, otherwise the output value maybe out of range.
In figure 1, it is easier, just find the corresponding KC value in the hidden vector for students' knowledge state.

**Comment by kwonmha** [comment]
TY. I got it.
So, the row vector of h matrix would be the proficiency vector of particular KC. 
And is sigmoid would be proper to get output from summed vector value?

And, for DKT, is hidden vector size of DKT same as the number of KC?
For example, if I use DKT for ASSIST2012 which has 265 conceps, the hidden size should be same?
